server:
  port: 8090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: nalsee
  main:
    allow-bean-definition-overriding: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
        web.socket: DEBUG
